version: '3.8'

services:

  app:
    build:
      context: ./app
      args:
        GITHUB_REPO: ${GITHUB_REPO}
    image: nuxt-app-image
    container_name: nuxt-app
    ports:
      - "3000:3000"
    environment:
      GITHUB_REPO: ${GITHUB_REPO}
      NODE_ENV: production # Définit l'environnement en mode production
    restart: always # Redémarre automatiquement le conteneur en cas de plantage
    networks:
      - ci_network
    depends_on:
      - jenkins


  jenkins:
    build:
        context: ./jenkins
    image: custom-jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080 # Options pour Jenkins
      # JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Monter uniquement le socket Docker si nécessaire
    networks:
      - ci_network

  

  # sonarqube:
  #   container_name: sonarqube
  #   image: sonarqube:latest
  #   environment:
  #     SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
  #     SONAR_JDBC_USERNAME: sonar
  #     SONAR_JDBC_PASSWORD: sonar
  #   volumes:
  #     - sonarqube_conf:/opt/sonarqube/conf
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - ci_network
  #   depends_on:
  #     - postgres

  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonar
  #     POSTGRES_DB: sonar
  #   volumes:
  #     - sonarqube_database:/var/lib/postgresql
  #     - sonarqube_database_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - ci_network

networks:
  ci_network:
    driver: bridge

volumes:
  # sonarqube_database_data:
  # sonarqube_bundled-plugins:
  # sonarqube_conf:
  # sonarqube_data:
  # sonarqube_database:
  # sonarqube_extensions:
  jenkins_home:
